### ISSUE TITLE
공지 페이지 데스크탑 레이아웃

### ISSUE THREAD

**Issue by ohchanju3** [Young-Camper/YoungCamper_FE#10]
## 📄 설명
공지페이지 데스크탑 레이아웃을 구현합니다.
공지페이지는 목록 페이지, 디테일 페이지로 구분되어있습니다. 
이 이슈에서는 데스크탑을 기준으로 구현하는걸 목표로 합니다.

## ✔️TO-DO
- [x] 받아오는 데이터 없을시 더미데이터가 보이도록 

__목록페이지__
- [x]  검색어
- [x] 번호, 제목, 날짜 레이아웃
- [x] pagination(5페이지 이상 넘어갈시 화살표 처리)
- [x] 공지 고정 (최상단) 

__디테일 페이지__
- [x] 디테일 페이지 레이아웃 구현
