### ISSUE TITLE
기획단 페이지 수정

### ISSUE THREAD

**Issue by ksinji** [Young-Camper/YoungCamper_FE#104]
## 📄 설명
기획단 페이지 데이터를 수정합니다.
## ✔️TO-DO
- [x] 기본 이미지 변경 -> 로고 등으로
- [x] 기획위원단 데이터 수정
- [x] 영캠퍼 데이터 수정
- [x] 상세 설명 폰트 색상 수정
- [x] 9/4 디자인 수정사항 반영
