### ISSUE TITLE
공연 안내 페이지 실제 데이터 변경

### ISSUE THREAD

**Issue by hyeona01** [Young-Camper/YoungCamper_FE#107]
## 📄 설명
기존 더미데이터를 실제 데이터로 변경합니다!

## ✔️TO-DO
- [x] 연예인 커버 이미지
- [x] 타임테이블 변경 예정
- [x] 상세 소개글-> 삭제
- [x] 대표곡
