### ISSUE TITLE
Navbar 데스크탑 레이아웃

### ISSUE THREAD

**Issue by penpenguin2018** [Young-Camper/YoungCamper_FE#11]
## 📄 설명
Nav를 이미 만들어주셨지만, 이슈 연습삼아 생성해보기

## ✔️TO-DO
- [ ] 로고 자리 잡아두기
- [ ] 스크롤해도 네비바가 고정되도록 만들기
- [ ] NavLink 사용해서, 현재 페이지 시각적으로 나타내기
