### ISSUE TITLE
Nav UIUX 디테일 수정

### ISSUE THREAD

**Issue by ohchanju3** [Young-Camper/YoungCamper_FE#111]
## 📄 설명
네브바 uiux 수정이 필요합니다.

## ✔️TO-DO
- [x] 모바일, 테블릿 버전에서의 padding 조정
- [x] 모바일, 테블릿 버전에서 한국어, 영어 글씨 부분에서 한국어 -> 영어 누르면 영어 버전이 된 후 다시 영어를 눌러도 한국어가 됩니다. 한국어를 누를 땐 한국어만, 영어를 누를땐 영어만 수정이 필요합니다.
- [x] 모바일, 테블릿 버전에서 한국어, ENG 부분 폰트 변경
