### ISSUE TITLE
FAQ 페이지 데스크탑 레이아웃

### ISSUE THREAD

**Issue by ksinji** [Young-Camper/YoungCamper_FE#12]
## 📄 설명
FAQ 페이지 데스크탑 레이아웃을 구현합니다.

## ✔️TO-DO
- [x] 전반적인 레이아웃 구성
- [x] 더미 데이터로 json 파일 만들기
- [x] 질의응답 컴포넌트 토글식으로 구현
