### ISSUE TITLE
홈페이지 QA 및 디테일 수정 반영

### ISSUE THREAD

**Issue by osein607** [Young-Camper/YoungCamper_FE#167]
## 📄 설명
홈페이지 가오픈 전 QA 및 디테일 수정 작업을 진행합니다.

## ✔️TO-DO
- [x] 타이틀 리스트 호버영역 = 링크 이동될 수 있게 연결
- [x] 반응형 깨지는 부분 맞추기
- [x] 동아리 슬라이드 속도 문제 
- [x] 동아리 사진 슬라이드마다 링크 연결
- [x] 공지사항 api 데이터 맞춰 수식 수정
