### ISSUE TITLE
모바일 navbar 만들기

### ISSUE THREAD

**Issue by penpenguin2018** [Young-Camper/YoungCamper_FE#37]
## ✔️TO-DO
- [x] 모바일 버전 navbar  구성
- [x] 사이드 네비바 버튼 만들기
- [x] 사이드 네비 만들기

**Comment by penpenguin2018** [comment]
반응형 웹을 구현할 때 styled component를 더 현명하게 쓰는 방법이 궁금합니다. 
ex) @media only screen and (min-width: 1024px) 이런식으로 값을 넣어서 모바일&데탑을 구분하고있는데, 이게 정답은 아닌것 같아서요!

**Comment by ohchanju3** [comment]
> 반응형 웹을 구현할 때 styled component를 더 현명하게 쓰는 방법이 궁금합니다. ex) @media only screen and (min-width: 1024px) 이런식으로 값을 넣어서 모바일&데탑을 구분하고있는데, 이게 정답은 아닌것 같아서요!

@penpenguin2018 혹시 해당 이슈 해결하셨을까용

**Comment by penpenguin2018** [comment]
아니요. 그냥 값 그대로 넣어서 구현해 뒀습니다 ㅠㅠ 혹시 더 좋은 방법이 궁금했던 건데, 다른 분들 코드도 참고해 가면서 해결해 보겠습니다 ㅎ
