### ISSUE TITLE
FAQ 페이지 반응형 구현

### ISSUE THREAD

**Issue by ksinji** [Young-Camper/YoungCamper_FE#39]
## 📄 설명
FAQ 페이지 반응형 레이아웃을 구현합니다.

## ✔️TO-DO
- [x] 답변박스 배경색 변경
- [x] 이미지 경로 수정
- [x] 반응형 레이아웃 구현
- [x] 모바일 뷰 페이지네이션 추가
