### ISSUE TITLE
About 페이지 수정된 레이아웃 구현

### ISSUE THREAD

**Issue by ksinji** [Young-Camper/YoungCamper_FE#46]
## 📄 설명
About 페이지의 수정된 레이아웃을 구현합니다.

## ✔️TO-DO
- [x] 상단 탭바 추가
- [x] 데스크탑 레이아웃 구현
- [x] 프로필카드 hover 설정
- [x] 프로필카드 상세설명 추가
- [x] 반응형 구현
