### ISSUE TITLE
홈페이지 태블릿, 모바일 레이아웃 구현

### ISSUE THREAD

**Issue by osein607** [Young-Camper/YoungCamper_FE#51]
## 📄 설명
홈페이지 태블릿 및 모바일 레이아웃을 구현합니다.

## ✔️TO-DO
- [x] 데스크탑 디자인 수정 반영
- [x] 데스크탑 코드 정리
- [x] 태블릿 반응형 구현
- [x] 모바일 반응형 구현
