### ISSUE TITLE
공연 안내페이지 레이아웃

### ISSUE THREAD

**Issue by hyeona01** [Young-Camper/YoungCamper_FE#6]
## 📄 설명
공연 안내 페이지에서 데스크탑 레이아웃을 완료합니다.

## ✔️TO-DO
- [x] 타임테이블 초기 레이아웃
- [x] 연예인 모달창 초기 레이아웃
- [x] 유의사항 레이아웃
- [x] 타임테이블 연예인 버전
- [x] 타임테이블 연예인 미공개 버전
- [x] 연예인 모달창
- [x] 모바일 반응형
- [x] 태블릿 반응형
