### ISSUE TITLE
About 페이지 페이지네이션 추가 및 이미지 AWS로 옮기기

### ISSUE THREAD

**Issue by ksinji** [Young-Camper/YoungCamper_FE#61]
## 📄 설명
About 페이지에 페이지네이션을 추가합니다.

## ✔️TO-DO
- [x] 한 페이지에 9개씩!
- [x] 페이지 바꾸면 위로 올라가도록 수정
- [x] 이미지 업로드
- [x] 코드에 경로 변경
- [x] 상세 설명 글자색 변경
