### ISSUE TITLE
공지페이지 세부적인 uiux

### ISSUE THREAD

**Issue by ohchanju3** [Young-Camper/YoungCamper_FE#84]
## 📄 설명
자체 qa를 바탕으로 생긴 공지사항 수정사항을 반영합니다.

## ✔️TO-DO
- [x] 공지사항 자동 상단 스크롤 위치 조정
- [x] 공지사항 반응형 디테일 (breakPoint 더 설정해서)
- [x] 폰트 변경된 것 확인 후 변경
- [x] 이미지 aws 경로로 수정
