### ISSUE TITLE
후기 페이지 데스크탑 레이아웃

### ISSUE THREAD

**Issue by dewbeeny** [Young-Camper/YoungCamper_FE#9]
## 📄 설명
후기 페이지 데스크탑 레이아웃을 짜고, 이슈 생성 및 활용 테스트 등 협업 연습을 합니다.

## ✔️TO-DO
- [x] 이슈 생성 및 활용
- [x] 커밋 및 pr 테스트
- [x] 후기페이지 데스크탑 레이아웃
