### ISSUE TITLE
FAQ 페이지 오타 수정 및 $ 추가

### ISSUE THREAD

**Issue by ksinji** [Young-Camper/YoungCamper_FE#90]
## 📄 설명
FAQ 페이지 오타를 수정하고 '$' 표시를 추가합니다.

## ✔️TO-DO
- [x] $ 표시 추가
- [x] 최대 너비 설정 다시하기
- [x] 디자인 수정 사항 반영
- [x] 이미지 경로 수정
