### ISSUE TITLE
홈페이지 더미 연결 및 원페이지 스크롤 구현, QA 반영

### ISSUE THREAD

**Issue by osein607** [Young-Camper/YoungCamper_FE#96]
## 📄 설명
홈페이지 더미 연결 및 원페이지 스크롤 구현
기타 QA를 반영합니다.

## ✔️TO-DO
- [x] 반응형 디테일 수정
- [x] 더미연결 (홍보영상, 유튜브 링크, 소셜 슬라이드 이미지)
- [ ] 원페이지 스크롤 구현
- [x] QA 반영
