### ISSUE TITLE
이미지 경로 재설정 및 코드 정리

### ISSUE THREAD

**Issue by hyeona01** [Young-Camper/YoungCamper_FE#97]
## 📄 설명
프로젝트 내의 이미지 경로 재설정

## ✔️TO-DO
- [x] assets 폴더 삭제
- [x] 이미지 경로 변경(S3 서버 경로)
- [x] 불필요한 코드 정리
